server:
  type: simple
  rootPath: /api/*
  applicationContextPath: /
  connector:
    type: http
    port: 8081

twitter:
  apiKey: AAABBBCCCDDD
  apiSecret: EEEFFFGGGHHH
  accountKey: IIIJJJKKKLLL
  accountSecret: MMMNNNOOOPPP

zodiac:
  twitterTrackTerms: pisces,scorpio
  tweetHistoryLength: 100

logging:
  level: INFO
  appenders:
    - type: console
      threshold: ALL
      timeZone: UTC
      target: stdout
